# 配置数据源及 JPA 相关
spring:
  datasource:
    username: beiran
    password: 123456
    url: jdbc:mysql://localhost:3306/erp-server-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 6