# 配置 debug 模式是否开启
debug: false

# 配置数据源及 JPA 相关
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # 配置 Spring MVC 相关属性
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  # 配置 Jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  # Redis 配置
  redis:
    timeout: 5000
  # 上传文件配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

# 配置服务器相关
server:
  port: 9001
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy: FRAMEWORK

# JWT 配置
jwt:
  # 密钥 KEY
  secret: ${jwt-secret:7196371f9fa2480696c74b152732cac1}
  token-header: Authorization
  token-prefix: ERP-
  expiration: 86400
  ant-matchers: /login,/swagger-ui.html,/swagger-resources/**,/v2/api-docs,/webjars/springfox-swagger-ui/**,/api/v1/auth/**,/webjars/**

# 常用配置
common:
  login-url: /api/v1/auth/login
  logout-url: /api/v1/auth/logout
  api-version: /api/v1
  code-key: codeKey

# 凤凰配置
phoenix:
  chinese-name: ${chinese-name}
  english-name: ${english-name}
  address: ${address}
  official-website: ${official-website}
  custom:
    logo: true
    outer-packing: true
    design: true

# 外部 API 相关配置
external:
  app-key: ${app-key}
  rate-url: ${rate-url}