# 配置数据源及 JPA 相关
spring:
  datasource:
    username: ${database-username}
    password: ${database-password}
    url: jdbc:mysql://${database-url}:${database-port}/${database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: ${redis-port}
    password: ${redis-password}
    database: 6